name: Quality And Build Check

on:
  workflow_dispatch:

jobs:
  quality-and-build-check:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Colombo"

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - run: npm ci
      #      - run: npm run check-format
      - run: npm run check-lint
      - run: npm run test:coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 3
      - run: npm run build
